# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: David Osuna  # Name of your website
tagline: Links  # Set your preferred page title
description: ...
favicon:
  path: assets/images/favicon.png
  type: png # File format of image. Change according to your image. Supported types: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
logo: assets/images/avatar.jpg
url: https://www.davidosuna.eu
locale: es_ES
image:
  path: assets/images/example.jpg # Used for SEO (og:image, twitter:image)
  type: jpeg # File format of image.
  height: 100 # Pixels
  width: 100
  alt: logo

# Verified Badge Configuration
badge:
  enable: false
  icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
  color: '#dfb221'  # Define the color of the badge

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
